import type { Player } from './types';

export const mockPlayers: Player[] = [
  {
    id: 'p001',
    name: 'James Thornton',
    bowlingStyle: 'Right Arm Fast',
    addedDate: '2026-01-15',
    email: 'james.thornton@cricketclub.com',
    ageGroup: 'Senior',
    club: 'Brisbane Tigers CC',
    coachAssigned: 'Coach Sukhi',
    guardianConsentStatus: 'N/A',
    subscription: {
      plan: 'Coach Pro',
      startDate: '2026-01-15',
      endDate: '2026-12-15',
      sessionsUsed: 14,
      sessionsLimit: 25,
    },
    biomechanics: {
      ballSpeedKmh: 138.4,
      frontKneeAngleDeg: 168,
      actionType: 'Side-on',
      injuryRisk: 'Low',
      lastSession: '2026-06-20',
    },
    academy: {
      stage: 'Mechanics',
      completionPercent: 62,
      totalSessions: 14,
      xp: 1840,
      articlesRead: 10,
    },
    sessionsCount: 14,
    lastActive: '2026-06-20',
    xp: 1840,
  },
  {
    id: 'p002',
    name: 'Arjun Patel',
    bowlingStyle: 'Right Arm Fast-Medium',
    addedDate: '2026-02-08',
    email: 'arjun.patel@gmail.com',
    ageGroup: 'U19',
    club: 'Sydney Royals CC',
    coachAssigned: 'Coach Sukhi',
    guardianConsentStatus: 'Confirmed',
    subscription: {
      plan: 'Player Pro',
      startDate: '2026-02-08',
      endDate: '2026-09-08',
      sessionsUsed: 9,
      sessionsLimit: null,
    },
    biomechanics: {
      ballSpeedKmh: 124.7,
      frontKneeAngleDeg: 172,
      actionType: 'Front-on',
      injuryRisk: 'Low',
      lastSession: '2026-06-18',
    },
    academy: {
      stage: 'Foundation',
      completionPercent: 85,
      totalSessions: 9,
      xp: 950,
      articlesRead: 6,
    },
    sessionsCount: 9,
    lastActive: '2026-06-18',
    xp: 950,
  },
  {
    id: 'p003',
    name: 'Mitchell Hayes',
    bowlingStyle: 'Left Arm Fast',
    addedDate: '2025-12-01',
    email: 'm.hayes@velocitycc.com',
    ageGroup: 'Senior',
    club: 'Velocity CC',
    coachAssigned: 'Coach Sukhi',
    guardianConsentStatus: 'N/A',
    subscription: {
      plan: 'Coach Pro',
      startDate: '2025-12-29',
      endDate: '2026-06-29',
      sessionsUsed: 22,
      sessionsLimit: 25,
    },
    biomechanics: {
      ballSpeedKmh: 143.1,
      frontKneeAngleDeg: 155,
      actionType: 'Mixed',
      injuryRisk: 'Moderate',
      lastSession: '2026-06-22',
    },
    academy: {
      stage: 'Velocity',
      completionPercent: 45,
      totalSessions: 22,
      xp: 3250,
      articlesRead: 18,
    },
    sessionsCount: 22,
    lastActive: '2026-06-22',
    xp: 3250,
  },
  {
    id: 'p004',
    name: 'Callum Richards',
    bowlingStyle: 'Right Arm Fast',
    addedDate: '2026-01-01',
    email: 'callum.r@sportmail.com',
    ageGroup: 'U19',
    club: 'Gold Coast Fast CC',
    coachAssigned: 'Coach Sukhi',
    guardianConsentStatus: 'Confirmed',
    subscription: {
      plan: 'Player Pro',
      startDate: '2026-01-01',
      endDate: '2026-07-01',
      sessionsUsed: 6,
      sessionsLimit: null,
    },
    biomechanics: {
      ballSpeedKmh: 118.9,
      frontKneeAngleDeg: 164,
      actionType: 'Side-on',
      injuryRisk: 'Low',
      lastSession: '2026-06-15',
    },
    academy: {
      stage: 'Foundation',
      completionPercent: 57,
      totalSessions: 6,
      xp: 650,
      articlesRead: 4,
    },
    sessionsCount: 6,
    lastActive: '2026-06-15',
    xp: 650,
  },
  {
    id: 'p005',
    name: 'Tom Davidson',
    bowlingStyle: 'Right Arm Medium',
    addedDate: '2025-11-20',
    email: 't.davidson@mail.com',
    ageGroup: 'Senior',
    club: 'Northside CC',
    coachAssigned: 'Coach Sukhi',
    guardianConsentStatus: 'N/A',
    subscription: {
      plan: 'Player Pro',
      startDate: '2025-11-20',
      endDate: '2026-05-20',
      sessionsUsed: 11,
      sessionsLimit: null,
    },
    biomechanics: {
      ballSpeedKmh: 109.2,
      frontKneeAngleDeg: 160,
      actionType: 'Front-on',
      injuryRisk: 'Low',
      lastSession: '2026-05-10',
    },
    academy: {
      stage: 'Mechanics',
      completionPercent: 30,
      totalSessions: 11,
      xp: 1200,
      articlesRead: 8,
    },
    sessionsCount: 11,
    lastActive: '2026-05-10',
    xp: 1200,
  },
  {
    id: 'p006',
    name: 'Sam Fletcher',
    bowlingStyle: 'Left Arm Fast-Medium',
    addedDate: '2026-03-01',
    email: 'sam.fletcher@fletcherspeed.com',
    ageGroup: 'U16',
    club: 'Melbourne Pace Academy',
    coachAssigned: 'Coach Sukhi',
    guardianConsentStatus: 'Confirmed',
    subscription: {
      plan: 'Coach Pro',
      startDate: '2026-03-01',
      endDate: '2026-11-30',
      sessionsUsed: 17,
      sessionsLimit: 25,
    },
    biomechanics: {
      ballSpeedKmh: 115.5,
      frontKneeAngleDeg: 170,
      actionType: 'Side-on',
      injuryRisk: 'Low',
      lastSession: '2026-06-24',
    },
    academy: {
      stage: 'Mechanics',
      completionPercent: 78,
      totalSessions: 17,
      xp: 2100,
      articlesRead: 13,
    },
    sessionsCount: 17,
    lastActive: '2026-06-24',
    xp: 2100,
  },
  {
    id: 'p007',
    name: 'Ravi Kumar',
    bowlingStyle: 'Right Arm Fast',
    addedDate: '2026-04-10',
    email: 'ravi.k@crickethub.com',
    ageGroup: 'Senior',
    club: 'Adelaide Strikers CC',
    coachAssigned: 'Coach Sukhi',
    guardianConsentStatus: 'N/A',
    subscription: {
      plan: 'Player Pro',
      startDate: '2026-04-10',
      endDate: '2026-10-10',
      sessionsUsed: 7,
      sessionsLimit: null,
    },
    biomechanics: {
      ballSpeedKmh: 133.8,
      frontKneeAngleDeg: 162,
      actionType: 'Side-on',
      injuryRisk: 'Moderate',
      lastSession: '2026-06-21',
    },
    academy: {
      stage: 'Foundation',
      completionPercent: 100,
      totalSessions: 7,
      xp: 1050,
      articlesRead: 7,
    },
    sessionsCount: 7,
    lastActive: '2026-06-21',
    xp: 1050,
  },
  {
    id: 'p008',
    name: 'Jack Morris',
    bowlingStyle: 'Right Arm Fast-Medium',
    addedDate: '2026-02-14',
    email: 'jackmorris@freemail.com',
    ageGroup: 'U19',
    club: 'Perth Thunder CC',
    coachAssigned: 'Coach Sukhi',
    guardianConsentStatus: 'Confirmed',
    subscription: {
      plan: 'Free',
      startDate: '2026-02-14',
      endDate: '2026-03-14',
      sessionsUsed: 1,
      sessionsLimit: 1,
    },
    biomechanics: {
      ballSpeedKmh: 107.4,
      frontKneeAngleDeg: 158,
      actionType: 'Mixed',
      injuryRisk: 'High',
      lastSession: '2026-03-10',
    },
    academy: {
      stage: 'Foundation',
      completionPercent: 28,
      totalSessions: 1,
      xp: 150,
      articlesRead: 2,
    },
    sessionsCount: 1,
    lastActive: '2026-03-10',
    xp: 150,
  },
];

export function getPlayerById(id: string): Player | undefined {
  return mockPlayers.find((p) => p.id === id);
}
