/**
 * Regenerates tests/seed/schema-notes.md from the dev Supabase project's live
 * schema via PostgREST's OpenAPI introspection endpoint (no direct DB/SQL
 * access needed — this repo has no supabase/migrations, so the hosted project
 * is the only source of truth for the schema's *structure*). Run after any
 * migration that adds/changes a table so schema-notes.md stays accurate.
 *
 * IMPORTANT — this file's prose is NOT stored in the database. Postgres
 * COMMENT ON COLUMN/TABLE was never actually used here; the only descriptions
 * PostgREST's OpenAPI endpoint returns are its own auto-generated "This is a
 * Primary/Foreign Key" notes. Every other explanation in schema-notes.md (why
 * a column exists, its valid values, append-only tables, etc.) was hand-typed
 * directly into this markdown file by whoever documented it. A naive
 * overwrite-the-whole-file regeneration destroys all of that permanently —
 * this happened for real once already. So this script MERGES: it reads the
 * existing schema-notes.md first and carries forward every hand-written
 * table-level paragraph and column note for anything that still exists in the
 * live schema, only ever touching an entry when the live schema actually
 * added/removed/renamed something. New columns/tables get an empty note for a
 * human to fill in later — never silently blank out an existing one.
 *
 * Usage: npx tsx tests/seed/introspect-schema.ts
 * Requires NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY in .env.local.
 */
import { config } from "dotenv";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import path from "node:path";

config({ path: path.resolve(__dirname, "../../.env.local") });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  throw new Error("NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set in web/.env.local");
}

interface ColumnDef {
  type: string;
  format: string;
  default?: unknown;
  description?: string;
}

interface TableDef {
  type: string;
  required?: string[];
  properties: Record<string, ColumnDef>;
}

interface OpenApiSchema {
  definitions: Record<string, TableDef>;
}

interface ExistingTable {
  /** Freeform hand-written paragraph(s) between the heading and the column table, if any. */
  description: string;
  /** column name -> hand-written notes cell content. */
  columnNotes: Record<string, string>;
}

/** PostgREST's own auto-generated PK/FK annotations — never worth preserving as "hand-written"
 * since the fresh introspection regenerates the identical text itself every time. Only real
 * prose beyond this is treated as manually authored and worth protecting from being overwritten. */
function isAutoGeneratedNote(note: string): boolean {
  return /^Note:\s*This is a (Primary|Foreign) Key/.test(note.trim());
}

/** Parses the previously-committed schema-notes.md (if any) into per-table hand-written content,
 * so a fresh regeneration can carry it forward instead of silently discarding it. */
function parseExisting(markdown: string): Record<string, ExistingTable> {
  const tables: Record<string, ExistingTable> = {};
  const tableBlocks = markdown.split(/^## `/m).slice(1);
  for (const block of tableBlocks) {
    const nameMatch = block.match(/^(\w+)`/);
    if (!nameMatch) continue;
    const name = nameMatch[1];
    const body = block.slice(nameMatch[0].length);

    const rows = body.split("\n").filter((l) => l.startsWith("|"));
    const dataRows = rows.filter((l) => !/^\|\s*column\s*\|/.test(l) && !/^\|\s*---/.test(l));
    const columnNotes: Record<string, string> = {};
    for (const row of dataRows) {
      // Split on unescaped pipes only — a notes cell can itself contain a literal markdown-escaped
      // "\|" (e.g. `"manual" \| "csv-import"`), which a naive row.split("|") breaks mid-cell on.
      const cells = row.split(/(?<!\\)\|/).map((c) => c.trim());
      // ["", column, type, nullable, default, notes, ""]
      if (cells.length < 6) continue;
      const col = cells[1];
      const notes = cells[5];
      if (col && notes) columnNotes[col] = notes;
    }

    // Everything between the heading and the first "| column |" header row, if non-blank, is a
    // hand-written table-level description — the script itself never emits one.
    const headerIdx = body.indexOf("| column |");
    const beforeTable = headerIdx >= 0 ? body.slice(0, headerIdx) : "";
    const description = beforeTable.replace(/\n+/g, " ").trim();

    tables[name] = { description, columnNotes };
  }
  return tables;
}

async function main() {
  const outPath = path.resolve(__dirname, "schema-notes.md");
  const existing: Record<string, ExistingTable> = existsSync(outPath)
    ? parseExisting(readFileSync(outPath, "utf-8"))
    : {};

  const res = await fetch(`${SUPABASE_URL}/rest/v1/`, {
    headers: {
      apikey: SERVICE_ROLE_KEY!,
      Authorization: `Bearer ${SERVICE_ROLE_KEY}`,
      Accept: "application/openapi+json",
    },
  });
  if (!res.ok) {
    throw new Error(`PostgREST introspection failed: ${res.status} ${await res.text()}`);
  }
  const schema = (await res.json()) as OpenApiSchema;
  const tableNames = Object.keys(schema.definitions).sort();

  const lines: string[] = [
    "# Dev Supabase schema (introspected)",
    "",
    `Structure generated by \`tests/seed/introspect-schema.ts\` against the dev project (${SUPABASE_URL}); prose notes are hand-written and merged forward on every regeneration, never overwritten — see this script's own doc comment. Regenerate after any schema change — this repo has no \`supabase/migrations\`, so this file (plus manual annotation) is the only schema documentation that exists.`,
    "",
    `**${tableNames.length} tables.**`,
    "",
  ];

  let newColumns = 0;
  let droppedTables = 0;
  for (const oldTable of Object.keys(existing)) {
    if (!tableNames.includes(oldTable)) droppedTables++;
  }

  for (const table of tableNames) {
    const def = schema.definitions[table];
    const required = new Set(def.required ?? []);
    const prior = existing[table];

    lines.push(`## \`${table}\``, "");
    if (prior?.description) lines.push(prior.description, "");
    lines.push("| column | type | nullable | default | notes |", "|---|---|---|---|---|");

    for (const [col, colDef] of Object.entries(def.properties)) {
      const nullable = required.has(col) ? "no" : "yes";
      const defaultVal = colDef.default !== undefined ? `\`${JSON.stringify(colDef.default)}\`` : "";
      const freshNote = (colDef.description ?? "").replace(/\n/g, " ").replace(/<[^>]+>/g, "").trim();
      const priorNote = prior?.columnNotes[col];
      // Prefer the hand-written note over the fresh one — the fresh one is either empty or one
      // of PostgREST's own auto-generated PK/FK notes, which carries no information a prior
      // hand-written note wouldn't already include (and if a column is genuinely new, there's no
      // prior note to prefer, so the fresh — possibly empty — note is all there is).
      const notes = priorNote && !isAutoGeneratedNote(priorNote) ? priorNote : (priorNote ?? freshNote);
      if (!prior?.columnNotes[col] && !freshNote) newColumns++;
      lines.push(`| ${col} | ${colDef.format} | ${nullable} | ${defaultVal} | ${notes} |`);
    }
    lines.push("");
  }

  writeFileSync(outPath, lines.join("\n"), "utf-8");
  console.log(`Wrote ${outPath} (${tableNames.length} tables)`);
  if (droppedTables > 0) console.log(`${droppedTables} previously-documented table(s) no longer exist in the live schema and were dropped from this file.`);
  if (newColumns > 0) console.log(`${newColumns} column(s) have no notes yet (new, or never annotated) — consider documenting them by hand.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
