/**
 * Regenerates tests/seed/schema-notes.md from the dev Supabase project's live
 * schema via PostgREST's OpenAPI introspection endpoint (no direct DB/SQL
 * access needed — this repo has no supabase/migrations, so the hosted project
 * is the only source of truth for the schema). Run after any migration that
 * adds/changes a table so schema-notes.md stays accurate.
 *
 * Usage: npx tsx tests/seed/introspect-schema.ts
 * Requires NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY in .env.local.
 */
import { config } from "dotenv";
import { writeFileSync } from "node:fs";
import path from "node:path";

config({ path: path.resolve(__dirname, "../../.env.local") });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  throw new Error("NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set in web/.env.local");
}

interface ColumnDef {
  type: string;
  format: string;
  default?: unknown;
  description?: string;
}

interface TableDef {
  type: string;
  required?: string[];
  properties: Record<string, ColumnDef>;
}

interface OpenApiSchema {
  definitions: Record<string, TableDef>;
}

async function main() {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/`, {
    headers: {
      apikey: SERVICE_ROLE_KEY!,
      Authorization: `Bearer ${SERVICE_ROLE_KEY}`,
      Accept: "application/openapi+json",
    },
  });
  if (!res.ok) {
    throw new Error(`PostgREST introspection failed: ${res.status} ${await res.text()}`);
  }
  const schema = (await res.json()) as OpenApiSchema;
  const tableNames = Object.keys(schema.definitions).sort();

  const lines: string[] = [
    "# Dev Supabase schema (introspected)",
    "",
    `Generated by \`tests/seed/introspect-schema.ts\` against the dev project (${SUPABASE_URL}). Regenerate after any schema change — this repo has no \`supabase/migrations\`, so this file (and the live dev project) is the only schema documentation that exists.`,
    "",
    `**${tableNames.length} tables.**`,
    "",
  ];

  for (const table of tableNames) {
    const def = schema.definitions[table];
    const required = new Set(def.required ?? []);
    lines.push(`## \`${table}\``, "", "| column | type | nullable | default | notes |", "|---|---|---|---|---|");
    for (const [col, colDef] of Object.entries(def.properties)) {
      const nullable = required.has(col) ? "no" : "yes";
      const defaultVal = colDef.default !== undefined ? `\`${JSON.stringify(colDef.default)}\`` : "";
      const notes = (colDef.description ?? "").replace(/\n/g, " ").replace(/<[^>]+>/g, "").trim();
      lines.push(`| ${col} | ${colDef.format} | ${nullable} | ${defaultVal} | ${notes} |`);
    }
    lines.push("");
  }

  const outPath = path.resolve(__dirname, "schema-notes.md");
  writeFileSync(outPath, lines.join("\n"), "utf-8");
  console.log(`Wrote ${outPath} (${tableNames.length} tables)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
