/**
 * Deletes all e2e-prefixed DB rows, then re-seeds — run before each E2E pass
 * so runs are deterministic regardless of what a previous run's tests
 * mutated. Never touches the auth users themselves (recreating those per run
 * is wasteful; seed.ts already keeps their metadata/password in sync).
 *
 * Usage: npm run seed:reset
 */
import { E2E_PREFIX, serviceClient } from "./client";
import { PLAYER_ENTITY_ID } from "./fixtures";
import { runSeed } from "./seed";

// Deletion order matters: coaches.academy_id is a real FK to academies, so
// coaches must go before academies. players.coach_id has no DB-level FK
// (app-level reference only, per schema-notes.md), so its order relative to
// coaches doesn't matter, but it's deleted first for clarity. reports
// references players the same (app-level only) way, deleted first regardless.
// bookings/session_packs were added for the credit-to-pack E2E fixture —
// both carry a real player_id FK, so they must go before players.
const TABLES_IN_DELETE_ORDER = ["reports", "bookings", "session_packs", "players", "coaches", "academies"] as const;

async function main() {
  const supabase = serviceClient();

  // Session rows aren't e2e-prefixed (ids are `s_${Date.now()}`, generated by
  // NewSessionForm), so the id-prefix sweep below can't find them — deleted
  // separately by player_id instead. video-pipeline.spec.ts (@slow) creates
  // one of these every run; without this they'd accumulate in the dev
  // project forever. (Their uploaded Storage blobs are a separate, still-open
  // cleanup gap — see AGENTS.md/schema-notes.md.)
  const { error: sessionsError } = await supabase.from("sessions").delete().eq("player_id", PLAYER_ENTITY_ID);
  if (sessionsError) throw new Error(`Failed to reset sessions: ${sessionsError.message}`);
  console.log("Reset sessions");

  // Same story for action_plans (ids are `ap_${Date.now()}`, generated by
  // /api/generate-action-plan) — generate-action-plan.spec.ts hits the real
  // Anthropic API and inserts a new one every run. Without this, each run
  // adds another "Coach notes" card on top of the last, and the spec's own
  // unscoped getByText("Coach notes") eventually hits a Playwright
  // strict-mode violation once there's more than one.
  const { error: actionPlansError } = await supabase.from("action_plans").delete().eq("player_id", PLAYER_ENTITY_ID);
  if (actionPlansError) throw new Error(`Failed to reset action_plans: ${actionPlansError.message}`);
  console.log("Reset action_plans");

  // academies.head_coach_id -> coaches is a real FK the other direction from
  // coaches.academy_id -> academies, so the two tables can block each other's
  // deletion depending on which app flow ran during the E2E pass (e.g. a
  // coach-role spec assigning itself head coach). Clear it first so coaches
  // can always be deleted regardless of what state a prior run left behind.
  const { error: headCoachError } = await supabase.from("academies").update({ head_coach_id: "" }).like("id", `${E2E_PREFIX}%`);
  if (headCoachError) throw new Error(`Failed to clear head_coach_id: ${headCoachError.message}`);

  for (const table of TABLES_IN_DELETE_ORDER) {
    const { error } = await supabase.from(table).delete().like("id", `${E2E_PREFIX}%`);
    if (error) throw new Error(`Failed to reset ${table}: ${error.message}`);
    console.log(`Reset ${table}`);
  }

  await runSeed();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
